### ISSUE TITLE
Not recognized in Lovelace

### ISSUE THREAD

**Issue by klotzma** [iobroker-community-adapters/ioBroker.accuweather#15]
If I add "Weather Summary" in the Any room and the Weather function, it will not be automatically recognized by Lovelace.

**Comment by algar42** [comment]
You also need to get type-detector from my repo - https://github.com/algar42/ioBroker.type-detector
Unfortunately blueFox does not want to merge it to main repo with my update to weather detection, and I can't make the update he want, because I don't have any other weather adapters installed in my sytem :(

**Comment by Garfonso** [comment]
> 
> 
> If I add "Weather Summary" in the Any room and the Weather function, it will not be automatically recognized by Lovelace.

This should be fixed if PR #69 is merged.

**Comment by algar42** [comment]
Yes this works with updated accuweather v1.2.0. 
I also PR'd two updates to LoveLace and Type-detector adapters to get the custom weather card (https://github.com/algar42/IoB.lovelace.accuweather-card) working:
![image](https://user-images.githubusercontent.com/40002726/124377727-1afed900-dcb6-11eb-8006-4d736df4e8c5.png)

Looks Ok now. Thanks @Garfonso :)
