### ISSUE TITLE
Fixed Datapoints für hourly Weatherdata

### ISSUE THREAD

**Issue by Fritzelspitze** [iobroker-community-adapters/ioBroker.accuweather#158]
To use the preview of the next hours, it would be great if the data is updated hourly and always written to fixed data points. The weather for in 4 hours should be in datapoint h4. This would allow me to easily preview the next 4 hours. Currently I would have to rotate the 24 data points somehow and there I just have no idea how to implement this reasonably in VIS.

**Comment by algar42** [comment]
First of all it is not possible to update hour-by-hour data every hour because free API access is limited to 50 requests per day and adapter is already uses 25 requests, excluding 12-hours data and 30 requests including them. If we add another 24 requests we will not have any room for possible adapter restarts. 
If you need to get data every hour and populate data to fixed datapoints you can create your own states using script. 
For example:
~~~
createState('0_userdata.0.weather.next4hours.n1.temp', 0);
createState('0_userdata.0.weather.next4hours.n2.temp', 0);
createState('0_userdata.0.weather.next4hours.n3.temp', 0);
createState('0_userdata.0.weather.next4hours.n4.temp', 0);

function getFixed() {
    const d = new Date();
    let hour = d.getHours(); //get current hour

    for (let i = 1; i < 4; i++) {
        setState('0_userdata.0.weather.next4hours.n' + i + '.temp', getState('accuweather.0.Hourly.h' + (hour+i) + '.Temperature').val);
    }
}

//create 'every hour' schedule
on('{"time":{"start":"00:00","end":"24:00","mode":"hours","interval":1},"period":{"days":1}}', ()=>{
    setStateDelayed('accuweather.0.updateHourly',true,15000); //Initiate 12-hours data update with 15 seconds delay after start of hour;
    setTimeout(getFixed,30000); //update fixed timepoints data with 30 seconds delay;
});
~~~

This script creates 4 temperature states and populates them every hour with temperature data from accuweather hourly report. 
Say, if current hour is 18, then n1.temp with take value from h19, n2.temp from h20 etc.. 
You can easily update this script for other data you need.

**Comment by Fritzelspitze** [comment]
Thank you very much! I can't write something like this from scratch in JS. But when you put it in front of me I understand it and can even improve it. If there should be a day jump (e.g. around 22 o'clock), it subtracts 23 hours to get from "25 o'clock" to "2 o'clock" and display the temperature correctly.

`function getFixed() {
    const d = new Date();
    let hour = d.getHours(); //get current hour

    for (let i = 1; i <= 7; i++) {
        let time = hour+i;
        if(time > 23)
            time = time-24;

        setState('0_userdata.0.weather.next4hours.n' + i + '.temp', getState('accuweather.0.Hourly.h' + (time) + '.Temperature').val);
    }
}`
